name: 'Deploy Action'

description: 'Action to deploy code via secure copy and ssh key'

author: 'Tanveer Karim'

inputs:
  user:
    description: 'Remote user'
    required: true

  host:
    description: 'Remote host'
    required: true

  port:
    description: 'Remote port'
    required: false
    default: 22

  key:
    description: 'Remote ssh key'
    required: true

  local_path:
    description: 'Local file location'
    required: true

  remote_path:
    description: 'Remote file location'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
